# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_evidence_augmentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.IntegerField()),
                ('collection_name', models.CharField(max_length=128)),
            ],
        ),
    ]
