# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='collection',
            name='num_pubs',
            field=models.IntegerField(default=0),
        ),
    ]
